### ISSUE TITLE
BLS failed for a target

### ISSUE THREAD

**Issue by orionlee** [noraeisner/LATTE#26]
The BLS analysis failed for a target TIC 364395234 . There is no error message indicating the reasons.
- The same input worked if I BLS is set to `no`
- I also tried to run basic BLS with `astropy` against the same LC file in the same environment. It ran without error.

```
Nearest neighbour plot... done.
Running BLS algorithm... Detrend data prior to BLS analysis... done.
TIC 364395234 failed to complete. Continue anyway. You can find a list of the failed IDs stored in the output folder.

  Complete!
```

The input csv:

```csv
TICID,sectors,transits,BLS,model,FFI
364395234,28,"2062.635919999797,2064.0116139997967,2065.387307999797,2066.763001999797,2068.1386959997967,2069.5143899997965,2070.890083999797",yes,0,no
```

---

Version: `LATTE-dev` branch (unclear if it fails with `v1.0.0`)
Platform: Windows 10

**Comment by orionlee** [comment]
Another TIC that failed in the same stemp:

```csv
TICID,sectors,transits,BLS,model,FFI
38820496,28,"2063.28,2063.942,2064.604,2065.266,2065.916,2066.57",yes,0,no
```

**Comment by orionlee** [comment]
Update: The error happened after the first BLS completed. For the failed targets, I found the plot of the first BLS in the output (the `..._bls_first.png`), indicating the first BLS had completed.

**Comment by orionlee** [comment]
Error stacktrace is available when running in interactive mode. The error that occurred in running 2nd BLS: 
```
ValueError: The maximum transit duration must be shorter than the minimum period
```

Full stack trace:
```python
Running BLS algorithm... Detrend data prior to BLS analysis... done.
Traceback (most recent call last):
  File "C:\pkg\_winNonPortables\Anaconda3\envs\LATTE-dev\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\pkg\_winNonPortables\Anaconda3\envs\LATTE-dev\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\dev\_juypter\LATTE\LATTE\__main__.py", line 546, in <module>
    utils.interact_LATTE(tic, indir, syspath, sectors_all, sectors, ra, dec, args)  # the argument of whether to shos the images or not
  File "C:\dev\_juypter\LATTE\LATTE\LATTEutils.py", line 690, in interact_LATTE
    brew.brew_LATTE(tic, indir, syspath, transit_list, simple, BLS, model, save, DV, sectors, sectors_all, alltime, allflux, allflux_err, all_md, alltimebinned, allfluxbinned, allx1, allx2, ally1, ally2, alltime12, allfbkg, start_sec, end_sec, in_sec, tessmag, teff, srad, ra, dec, args)
  File "C:\dev\_juypter\LATTE\LATTE\LATTEbrew.py", line 330, in brew_LATTE
    bls_stats1, bls_stats2 = utils.data_bls(tic, indir, alltime, allflux, allfluxbinned, alltimebinned, args)
  File "C:\dev\_juypter\LATTE\LATTE\LATTEutils.py", line 4486, in data_bls
    in_transit = model.transit_mask(alltimebinned, period, 2*duration, t0)
  File "C:\pkg\_winNonPortables\Anaconda3\envs\LATTE-dev\lib\site-packages\astropy\timeseries\periodograms\bls\core.py", line 594, in transit_mask
    period, duration = self._validate_period_and_duration(period, duration)
  File "C:\pkg\_winNonPortables\Anaconda3\envs\LATTE-dev\lib\site-packages\astropy\timeseries\periodograms\bls\core.py", line 696, in _validate_period_and_duration
    raise ValueError("The maximum transit duration must be shorter "
ValueError: The maximum transit duration must be shorter than the minimum period
```
