### ISSUE TITLE
[LATTE-dev] Vetting in FFI mode hits AttributeError: 'TessTargetPixelFile' object has no attribute 'data'

### ISSUE THREAD

**Issue by orionlee** [noraeisner/LATTE#33]
With the same input as reported in #31, after I applied a [candidate fix](https://github.com/noraeisner/LATTE/issues/31#issuecomment-719975429) to get around the error there, I hit another error:

```python
Aperture size plots... done.
Downloading https://skyview.gsfc.nasa.gov/tempspace/fits/skv2260287077344.fits
|===========================================| 371k/371k (100.00%)         0s
Traceback (most recent call last):
  File "C:\pkg\_winNonPortables\Anaconda3\envs\LATTE-dev\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\pkg\_winNonPortables\Anaconda3\envs\LATTE-dev\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\dev\_juypter\LATTE\LATTE\__main__.py", line 544, in <module>
    utils.interact_LATTE_FFI(tic, indir, syspath, sectors_all, sectors, ra, dec, args)
  File "C:\dev\_juypter\LATTE\LATTE\LATTEutils.py", line 2111, in interact_LATTE_FFI
    brew.brew_LATTE_FFI(tic, indir, syspath, transit_list, simple, BLS, model, save, DV, sectors, sectors_all, alltime0, allflux_list, allflux_small, allflux0, all_md, allfbkg, allfbkg_t, start_sec, end_sec, in_sec, X1_list, X4_list, apmask_list, arrshape_list, tpf_filt_list, t_list, bkg_list, tpf_list, ra, dec, args)
  File "C:\dev\_juypter\LATTE\LATTE\LATTEbrew.py", line 558, in brew_LATTE_FFI
    tessmag, teff, srad, mstar,vmag, logg, plx, c_id = utils.plot_TESS_stars(tic,indir, transit_sec, tpf_list, args)
  File "C:\dev\_juypter\LATTE\LATTE\LATTEutils.py", line 5179, in plot_TESS_stars
    tup = (np.nanmean(tpf[1].data['FLUX'], axis=0),tpf_wcs)
AttributeError: 'TessTargetPixelFile' object has no attribute 'data'
```

It is as if the downloaded TESSCut `tpf` is corrupted.

Versions:
- LATTE: `LATTE-dev` latest with [candidate fix](https://github.com/noraeisner/LATTE/issues/31#issuecomment-719975429) 
- Lightkurve: v1.11.1
- numpy: 1.19.2
- platform: Windows

**Comment by orionlee** [comment]
The line that failed:

https://github.com/noraeisner/LATTE/blob/9f762f9a0497c561ee65c97262961df4ee0f5429/LATTE/LATTEutils.py#L5179

If it's reverted back to the older commit, it'd work:
```python
    tup = (np.nanmean(tpf[1].flux, axis=0),tpf_wcs)
```

If the intent is to get the FITS files' raw flux without any Lightkurve processing, it would be:
```python
    tup = (np.nanmean(tpf[1].hdu[1].data['FLUX'], axis=0),tpf_wcs)
```

The commit https://github.com/noraeisner/LATTE/commit/859a8ccfc9390dd8f037cd1852f216b91c327833#diff-8faef64cf39f8a748228c4c6cf800049bfa85b7f80639ecded41f76c87b0b4f5 has made similar changes in other parts of the codebase.
