### ISSUE TITLE
Hit ValueError during vetting

### ISSUE THREAD

**Issue by orionlee** [noraeisner/LATTE#8]
In trying to vet TIC 329342112 (see [PHT talk thread](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk/2112/1563334)), I got the following exception while LATTE was processing.

```
...
Downloading https://mast.stsci.edu/api/v0.1/Download/file/?uri=mast:TESS/product/tess2020133194932-s0025-0000000329342112-0182-s_tp.fits
|===========================================|  45M/ 45M (100.00%)      5m25s
Aperture size plots... done.
Downloading https://skyview.gsfc.nasa.gov/tempspace/fits/skv26484726564662.fits
|===========================================| 371k/371k (100.00%)         3s
Star Aperture plots... done.
Traceback (most recent call last):
  File "C:\pkg\Anaconda3\envs\forLATTE\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\pkg\Anaconda3\envs\forLATTE\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\dev\_juypter\LATTE\LATTE\__main__.py", line 426, in <module>
    utils.interact_LATTE(tic, indir, syspath, sectors_all, sectors, ra, dec, args)  # the argument of whether to shos the images or not
  File "c:\dev\_juypter\LATTE\LATTE\LATTEutils.py", line 661, in interact_LATTE
    brew.brew_LATTE(tic, indir, syspath, transit_list, simple, BLS, model, save, DV, sectors, sectors_all, alltime, allflux, allflux_err, all_md, alltimebinned, allfluxbinned, allx1, allx2, ally1, ally2, alltime12, allfbkg, start_sec, end_sec, in_sec, tessmag, teff, srad, ra, dec, args)
  File "c:\dev\_juypter\LATTE\LATTE\LATTEbrew.py", line 237, in brew_LATTE
    X1_list, X4_list, oot_list, intr_list, bkg_list, apmask_list, arrshape_list, t_list, T0_list, tpf_filt_list = utils.download_tpf_mast(indir, transit_sec, transit_list, tic)
  File "c:\dev\_juypter\LATTE\LATTE\LATTEutils.py", line 3765, in download_tpf_mast
    trends = pca.fit_transform(X2)
  File "C:\pkg\Anaconda3\envs\forLATTE\lib\site-packages\sklearn\decomposition\_pca.py", line 376, in fit_transform
    U, S, V = self._fit(X)
  File "C:\pkg\Anaconda3\envs\forLATTE\lib\site-packages\sklearn\decomposition\_pca.py", line 425, in _fit
    return self._fit_truncated(X, n_components, self._fit_svd_solver)
  File "C:\pkg\Anaconda3\envs\forLATTE\lib\site-packages\sklearn\decomposition\_pca.py", line 545, in _fit_truncated
    random_state=random_state)
  File "C:\pkg\Anaconda3\envs\forLATTE\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "C:\pkg\Anaconda3\envs\forLATTE\lib\site-packages\sklearn\utils\extmath.py", line 358, in randomized_svd
    Uhat, s, V = linalg.svd(B, full_matrices=False)
  File "C:\pkg\Anaconda3\envs\forLATTE\lib\site-packages\scipy\linalg\decomp_svd.py", line 106, in svd
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "C:\pkg\Anaconda3\envs\forLATTE\lib\site-packages\scipy\_lib\_util.py", line 263, in _asarray_validated
    a = toarray(a)
  File "C:\pkg\Anaconda3\envs\forLATTE\lib\site-packages\numpy\lib\function_base.py", line 486, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
```

It seemed to have created some array with `infs` or `NaNs` in making the following call in `download_tpf_mast`: https://github.com/noraeisner/LATTE/blob/f5423bcd0bcb7f26f593576c27dbea95db879201/LATTE/LATTEutils.py#L3765

The stacktrace is above generated from the latest LATTE codes in github. The same error happened with the released `v1.0.0`.

**Comment by orionlee** [comment]
The `ValueError` appears to be an installation issue that is probably specific to Windows (or some subset of Windows): during the installation via `pip`, some dependent packages are installed with bad version (that aren't quite completely working).

The workaround I used:

1. Before installing LATTE, first use `conda` to install the following packages (`conda` installation does a better job of skipping potentially bad versions, comparing to `pip`)
```
conda install --channel=conda-forge numpy scikit-learn scipy
```

2. Then follow the [normal installation instruction](https://github.com/noraeisner/LATTE/blob/master/README.md)
```
pip install tessLATTE
```

3. On Windows or Anaconda environment, you'd need to ensure `python3` exists. See https://github.com/noraeisner/LATTE/issues/7

**Comment by orionlee** [comment]
If LATTE is available on `conda-forge`, then the issue can probably be resolved without any workaround.
